### PR TITLE
Fix the ArffLoader bug in processing

### PR DESCRIPTION
**Pull request by asp188**
the "numAttribute" in ArffLoader must be added for each loop.

### CODE REVIEW

**Comment by abifet** [comment]
+1 (Please start the pull request with SAMOA-xx:)

**Comment by gdfm** [comment]
Thanks, could you please also open a Jira issue on https://issues.apache.org/jira/browse/SAMOA ?

**Comment by gdfm** [comment]
Oh, I guess this fixes SAMOA-26.

**Comment by gdfm** [comment]
Unfortunately the patch doesn't seem to solve the issue.
First, it would be good to write a test to isolate the issue.
By debugging the example in the Jira, I get the following metadata in Instances:
```
[@attribute Dur NUMERIC, @attribute Proto NUMERIC, @attribute Dir NUMERIC, @attribute State NUMERIC, @attribute sTos NUMERIC, @attribute dTos NUMERIC, @attribute TotPkts NUMERIC, @attribute TotBytes NUMERIC, @attribute SrcBytes NUMERIC, @attribute class NUMERIC]
```
There are several issues:
1) There is an issue with the toString method in Attribute (it always returns NUMERIC)
2) The ArffLoader does not handle well newlines before the definition of the set of values for a nominal attribute. By putting the attribute definition on a single line I managed to get the header parsed correctly.
```
[@attribute Dur NUMERIC, @attribute Proto NOMINAL, @attribute Dir NOMINAL, @attribute State NOMINAL, @attribute sTos NUMERIC, @attribute dTos NUMERIC, @attribute TotPkts NUMERIC, @attribute TotBytes NUMERIC, @attribute SrcBytes NUMERIC, @attribute class NOMINAL]
```
3) The characters '<->' and so on are not recognized as words by line 97 in ArffLoader
```
else if (streamTokenizer.sval != null && (streamTokenizer.ttype == StreamTokenizer.TT_WORD
              || streamTokenizer.ttype == 34)) {
```
The ttype value is 39, which corresponds to the single quote '.
By modifying the test arff file I managed to make it work.
I guess we could add an OR to the statement checking also for single quotes.

**Comment by abifet** [comment]
I added a test of ArffLoader in

https://github.com/abifet/incubator-samoa/commit/60a8541580ee21dfd052547e4ddd366e0ec7ab40

Please @asp188, can you add it to this pull request and check that it works?

**Comment by asp188** [comment]
all tests passed given your test case.

**Comment by asp188** [comment]
weird Travis  exit "The command "./gradlew s4-tools::installApp" failed and exited with 1 during ." I am not sure what happend

**Comment by asp188** [comment]
Seems something was wrong because  the travis system did not run correctly a  moment ago. Now everything is ok.

**Comment by abifet** [comment]
+1

**Comment by gdfm** [comment]
+1
Merged.
Thanks for the contribution!

**Pull request closed without merging**
