### PR TITLE
SAMOA-27: Storm upgrade to the latest stable version (0.9.4)

### PR DESCRIPTION
**Pull request by giacbrd**
Storm, and consequently Zookeeper and Kryo, have been updated.
Samoa-storm compiles and passes the tests; the example of CoverType dataset (classified with the bagging algorithm) runs without problems.
Also the code of my fork with a word2vec implementation runs correctly.

### CODE REVIEW

**Comment by gdfm** [comment]
Thanks!
I created [SAMOA-27](https://issues.apache.org/jira/browse/SAMOA-27) to track the PR.
Could you rename the PR by adding SAMOA-XX to the title (see e.g. #11)?

**Comment by gdfm** [comment]
All the tests pass.
Tested various runs of Bagging, VHT, and AMRules on Storm local model and they all work.
Also ran the ClusteringEvaluation. Seems to work but it's hard to evaluate :)

In the samoa script, given that now storm-core.jar is in the /lib directory of storm, we can simplify the line creating the class path by removing the STORM_JAR entry.

+1

**Comment by abifet** [comment]
+1

**Comment by gdfm** [comment]
Merged.
@giacbrd thanks for the contribution!

**Comment by giacbrd** [comment]
you're welcome!

2015-05-15 9:32 GMT+02:00 Gianmarco De Francisci Morales <
notifications@github.com>:

**Pull request closed without merging**
