### PR TITLE
SAMOA-51: Update Flink Module to v0.10.1

### PR DESCRIPTION
**Pull request by senorcarbone**
This patch upgrades the samoa-flink module to be compatible with Flink  0.10.1

### CODE REVIEW

**Comment by senorcarbone** [comment]
I tested VHT with 8 local workers and rather rather sufficient allocated memory (4GB) and it still takes a while, around 1m50sec. There will be an additional patch soon, probably collocated with Flink v1.0 that will address these performance issues on iterative streaming jobs. 

screen shot 2015-12-11 at 14 21 17

**Comment by senorcarbone** [comment]
@abifet @gdfm we could merge this if you are ok with it. Just let me know, whenever you have free time. 
There are not too many changes anyway. Mainly refactorings to comply with the new Flink streaming API. cheers!

**Comment by gdfm** [comment]
Thanks @senorcarbone, +1 for me.
Most of the changes seem cosmetic anyway.

**Comment by abifet** [comment]
Thanks @senorcarbone <https://github.com/senorcarbone>, +1 also for me.

**Pull request closed without merging**
