### PR TITLE
SAMOA-11: Incorrect String comparison in Clustering.java

### PR DESCRIPTION
**Pull request by smarthi**
Fixes SAMOA-11

### CODE REVIEW

**Comment by abifet** [comment]
+1 to merge this.

**Comment by smarthi** [comment]
Fixes SAMOA-11

**Comment by gdfm** [comment]
There seems to be a lot of formatting changes, but I cannot identify the gist of the patch.
What was the bug? Can you add a test to reproduce it?

**Comment by smarthi** [comment]
This PR predates the formatting changes that were committed later, hence u see all the formatting. I am thinking I'll close this PR and create another that has the fix.

**Comment by gdfm** [comment]
No need to open a new PR. Simply push the new code on the same branch.
We will take care of squashing it on our side.

**Comment by smarthi** [comment]
ok I'll update this PR, I squash my commits anyways before pushing a PR.

**Pull request closed without merging**
