### PR TITLE
SAMOA-3: Add documentation and update the website

### PR DESCRIPTION
**Pull request by abifet**

### CODE REVIEW

**Comment by gdfm** [comment]
+1

**Comment by gdfm** [comment]
@abifet given that we agreed on the bylaws, you can safely merge the PR.
I wold recommend squashing the changes in a single commit and labeling it with the Jira issue number in the comment:
"SAMOA-3: Add documentation and update the website"

**Comment by abifet** [comment]
Thanks @gdfm! Can you merge the PR? It seems that I do not have write access to this repository to merge pull requests.

**Comment by matthieumorel** [comment]
@abifet that's weird, you should be able to do that. Note that you need to merge locally ( from master: `git merge SAMOA-3 --no-ff` ) then push to the apache git repo ( `git push <name of the apache remote> master` ).

You cannot push to the github repo, nor use the merge buttons, because the github mirror is read only.

**Pull request closed without merging**
