### PR TITLE
SAMOA-36: Update Apache Flink Adapter to 0.9 stable release

### PR DESCRIPTION
**Pull request by senorcarbone**
This patch upgrades the Flink adapter to `0.9.0` stable release. It includes several bug fixes and performance improvements along with compatibility with the new operator interfaces of Flink. 

I got a x3 speedup on VHT compared to the previous version using a local cluster with 8 cores.

### CODE REVIEW

**Comment by gyfora** [comment]
Looks good to me, this is an important update. :+1:

**Comment by gdfm** [comment]
+1

**Comment by gdfm** [comment]
One small detail. The copyright in the pom.xml needs to be updated to the ASF and to the right years (see the main pom.xml for an example).

**Comment by senorcarbone** [comment]
@gdfm  Indeed, thanks for noticing. I just updated it and rebased

**Comment by gdfm** [comment]
Thanks. I'll commit this as soon as I get another +1.
In the meanwhile, given the new merge policy, could you prepend "SAMOA-36: " to the commit log?

**Comment by abifet** [comment]
+1

**Pull request merged**
