### PR TITLE
SAMOA-71: fixes concurrency issues in HorizontalAMRulesRegressor

### PR DESCRIPTION
**Pull request by mgrzenda**
I suggest a change in ruleSet implementation from LinkedList (providing fail-fast iterators, which causes ConcurrencyException when list content changes during iterating over it) to CopyOnWriteArrayList (which is a thread-safe variant eliminating concurrency exceptions). In the analysed case, the modifications to ruleSet are expected to be much less frequent than reading the rules. When the number of read operations is relatively large and update operations are far less frequent, a possible choice is CopyOnWriteArrayList.

I have compared the performance on 35k instance streams (with a higher than 35k number concurrency exception got thrown) and got the same <1 second processing time. Hence, the possible negative impact on the performance can be considered negligible, if any. Still, suggestions and possible other solution ideas from designers of AMRules are welcome.

### CODE REVIEW

**Comment by mgrzenda** [comment]
Recent automated builds ten to be slow and exceed timeouts. This commit increases the values limiting the time allocated to Storm tests. This is to prevent the failure of these tests and entire Travis build in turn.

**Comment by gdfm** [comment]
+1, looks good to me.
Thanks for the fix!

**Comment by abifet** [comment]
+1
Thanks! That's a nice improvement.

**Comment by djKooks** [comment]
Now test goes well. Thanks!

**Pull request closed without merging**
