### PR TITLE
SAMOA-34: Make ensemble methods work with all Learners

### PR DESCRIPTION
**Pull request by gdfm**
Note that Boosting does not work with this patch.
@abifet could you take a look at the logic in Boosting?
It's not clear to me how to fix it.

### CODE REVIEW

**Comment by gdfm** [comment]
Unfortunately the GitHub mirror hasn't synched with the Apache repository, so SAMOA-9 is included in the patch (even though it is already committed). I already asked INFRA to take a look. I guess this makes the patch hard to review.

**Comment by gdfm** [comment]
The tests actually pass, but Travis-CI is erroring out because the log size is > 4MB.

**Comment by abifet** [comment]
+1

**Comment by gdfm** [comment]
@abifet I think you merged a slightly stale version of the PR.
No big deal, I verified the only difference was in the commit log.
For next time it would be good if we make sure to do a pull on the PR branch before merging, and check that the tip of the branch in the log is the same as in the PR (i.e., the commit ids are the same).
In this case we merged 5f1e1a1 but the PR's tip was b448b12.

**Pull request closed without merging**
