### PR TITLE
SAMOA-67 : Integration of MOA Instances into SAMOA 

### PR DESCRIPTION
**Pull request by mehdidb**

### CODE REVIEW

**Comment by nicolas-kourtellis** [comment]
Is this related to #57 ? Does it superseed it? Does this mean #57 is deprecated? @abifet can you please check and give us the OK?

**Comment by mehdidb** [comment]
Hi, yes it's relate to #57.
Yes it's basically the same (this one is the new version with some change to the hsAttributeIndices and the first pull request has a problem in the title)  sorry for the inconvience.

**Comment by bigmine** [comment]
This code allows to manage multi-label instances for multi-label and multi-target learning.

I checked the code, and it's OK for me.

+1

I checked the difference in speed using the instances, and it seems that there is no difference in reading from a file, copying an instance, or getting values of an attribute inside an Instance. It seems that there is a difference on obtaining the class value of an instance, but it is not large.

**Comment by abifet** [comment]
This code allows to manage multi-label instances for multi-label and multi-target learning.

I checked the code, and it's OK for me.

+1

I checked the difference in speed using the instances, and it seems that there is no difference in reading from a file, copying an instance, or getting values of an attribute inside an Instance. It seems that there is a difference on obtaining the class value of an instance, but it is not large.

**Comment by nicolas-kourtellis** [comment]
Ok great, so lets go ahead and merge this.
+1

**Comment by nicolas-kourtellis** [comment]
@abifet @mehdidb , is there something we can do about these conflicting files?

**Comment by mehdidb** [comment]
@nicolas-kourtellis @abifet i have merged new samoa patches but to avoid problems i have created another pull request from the same code but the difference is that he has the new patches in it.

**Comment by gdfm** [comment]
@mehdidb thanks, there is no need for a new pull request. You can just rebase the code on the latest HEAD for SAMOA and update the current PR.

**Comment by mehdidb** [comment]
@gdfm Thanks, i have rebased the code on the lastest head for samoa.
Normally all the conflicts are corrected and it's should be ok.

**Comment by gdfm** [comment]
Hi @mehdidb,
I'm trying to merge the PR but I get a very unclean commit history when I rebase vs the current master:

pick dbfdc49 SAMOA-67 : Integration of MOA Instances into SAMOA
pick c3155a1 SAMOA-67 : Integration of MOA Instances into SAMOA
pick 455ae8f SAMOA-67 : Re-including hsAttributesIndices in Instances
pick 34622ab SAMOA-67 : Correction in Instances Header
pick 1c7a4c8 SAMOA-67 : Correct indentation
pick 69d2165 SAMOA-67 : Improvement in speed
pick 1f7ce52 SAMOA-67 : Improvement in speed
pick 28da2cf SAMOA-67 : Improvement in speed
pick 2ab6d4a SAMOA-67 : Corrections in AvroLoader and ArffLoader
pick f414739 SAMOA-67 : Merge new instances into new code

And it also fails the rebase.

I think it is because of these 2 commits:

commit c87fc6d74e5df85d5a36d32260c511b87685c2d2
Merge: 8275e84 dbc3aab
Author: mehdidb <mehdi.deboub@supcom.tn>
Date:   Thu Jul 6 12:44:34 2017 +0200

    Merge remote-tracking branch 'refs/remotes/apache/master'

    # Conflicts:

    #   samoa-instances/src/main/java/org/apache/samoa/instances/Attribute.java

    #   samoa-instances/src/main/java/org/apache/samoa/instances/DenseInstance.java

    #   samoa-instances/src/main/java/org/apache/samoa/instances/SingleLabelInstance.java

    #   samoa-instances/src/main/java/org/apache/samoa/instances/SparseInstance.java

commit 8275e849569a5e54099434244a5bfa2085c40030
Merge: 2ab6d4a a1cc237
Author: mehdidb <mehdi.deboub@supcom.tn>
Date:   Thu Jul 6 12:22:15 2017 +0200

    Merge remote-tracking branch 'refs/remotes/apache/master'


Could you try cleaning up your commit history and pushing a cleaned up PR with a single commit on top of the current HEAD of master?

**Pull request closed without merging**
